name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Poetry & Deps
        run: |
          python -m pip install poetry
          poetry install
      - name: Test Coverage
        run: make coverage
      - run: PYTHONPATH=src poetry run mkdocs gh-deploy --force
